### ISSUE TITLE
Display a TF tree using pinocchio model

### ISSUE THREAD

**Issue by whtqh** [tasts-robots/pink#13]
Dear Caron:
I found this repo by using Pinocchio when I tried to learn more about Meshcat, and thanks a lot for your code, I get some inspiration for drawing a TF tree for a robot model.
My understanding of this code in [pink](https://github.com/tasts-robots/pink/blob/510a702996411a4528b274b4351d53a20760a4be/examples/wheeled_biped_upkie.py#L83
)
```
meshcat_shapes.frame(viewer["left_contact_target"], opacity=0.5)
```
 is that we will replace the old object with a new frame.
My question is if we could just add the frame by using `addGeometryObject`?

Thanks for your help!
heaty

**Comment by stephane-caron** [comment]
Yep, both behaviors are possible. There is currently no particular reason why the object is replaced rather than added. Feel free to [open a PR](https://github.com/stephane-caron/meshcat-shapes/pulls) in [meshcat-shapes](https://github.com/stephane-caron/meshcat-shapes) if the additive behavior is better for your use case.
